/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-rfnoc_example
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_RFNOC_EXAMPLE_API_H
#define INCLUDED_RFNOC_EXAMPLE_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_rfnoc_example_EXPORTS
#define RFNOC_EXAMPLE_API __GR_ATTR_EXPORT
#else
#define RFNOC_EXAMPLE_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_RFNOC_EXAMPLE_API_H */
